[[repos]]
repo = "local"

[[repos.hooks]]
id = "cargo-fmt"
name = "cargo fmt"
language = "system"
entry = "cargo fmt"
types = ["rust"]
pass_filenames = false

[[repos.hooks]]
id = "cargo-clippy"
name = "cargo clippy"
language = "system"
entry = "cargo clippy -- -D warnings"
types = ["rust"]
pass_filenames = false

[[repos.hooks]]
id = "npm-lint"
name = "npm lint & fix"
language = "system"
entry = "npm run lint:fix"
files = "^frontend/"
pass_filenames = false

[[repos.hooks]]
id = "svelte-check"
name = "svelte check"
language = "system"
entry = "npm run svelte-check"
files = "^frontend/"
pass_filenames = false

[[repos.hooks]]
id = "npm-test"
name = "npm test"
language = "system"
entry = "npm test"
files = "^frontend/"
pass_filenames = false
