ALTER TABLE pull_requests ADD COLUMN body TEXT NOT NULL DEFAULT '';
ALTER TABLE pull_requests ADD COLUMN state TEXT NOT NULL DEFAULT 'open';
ALTER TABLE pull_requests ADD COLUMN head_sha TEXT NOT NULL DEFAULT '';
ALTER TABLE pull_requests ADD COLUMN additions INTEGER NOT NULL DEFAULT 0;
ALTER TABLE pull_requests ADD COLUMN deletions INTEGER NOT NULL DEFAULT 0;
ALTER TABLE pull_requests ADD COLUMN changed_files INTEGER NOT NULL DEFAULT 0;
