// Every type crossing the API/SSE boundary is generated from the Rust structs
// by ts-rs into ./generated (regenerated by `cargo test`). This module maps
// them onto the names the components use and adds the few frontend-only
// shapes. Never redefine an API payload by hand here — extend or alias the
// generated type instead.
import type { InboxItem as ApiInboxItem } from "./generated/InboxItem";
import type { PaginatedInbox as ApiPaginatedInbox } from "./generated/PaginatedInbox";
import type { PrInfoUpdatedData } from "./generated/PrInfoUpdatedData";

export type { CheckRunResponse as CheckRun } from "./generated/CheckRunResponse";
export type { CommentResponse as Comment } from "./generated/CommentResponse";
export type { CommitRow as Commit } from "./generated/CommitRow";
export type { InboxOptions as FilterOptions } from "./generated/InboxOptions";
export type { LabelResponse as Label } from "./generated/LabelResponse";
export type { PrDetailResponse } from "./generated/PrDetailResponse";
export type { PrStatus } from "./generated/PrStatus";
export type { PullRequestResponse as PullRequest } from "./generated/PullRequestResponse";
export type { ReviewResponse as Review } from "./generated/ReviewResponse";
export type { ThreadResponse as Thread } from "./generated/ThreadResponse";
export type { PrInfoUpdatedData };

export interface Notification {
    id: string;
    pr_id: number | null;
    title: string;
    repository: string;
    reason: string;
    unread: boolean;
    archived: boolean;
    updated_at: string;
}

/**
 * Inbox rows as the UI sees them: the API row plus activity fields merged
 * client-side from pr:info_updated SSE events. `undefined` = not yet enriched
 * (render nothing); `null` = first visit (never viewed).
 */
export interface InboxItem extends ApiInboxItem {
    new_commits?: PrInfoUpdatedData["new_commits"];
    new_comments?: PrInfoUpdatedData["new_comments"];
    new_reviews?: PrInfoUpdatedData["new_reviews"];
}

export interface PaginatedInbox extends Omit<ApiPaginatedInbox, "items"> {
    items: InboxItem[];
}

export const DEFAULT_PER_PAGE = 20;

export type Theme =
    | "system"
    | "light"
    | "dark"
    | "catppuccin-latte"
    | "catppuccin-frappe"
    | "catppuccin-macchiato"
    | "catppuccin-mocha";

export interface Preferences {
    theme: Theme;
}

export type StateFilterMode = "include" | "exclude";

export interface ActiveFilters {
    repo?: string;
    team?: string;
    author?: string;
    /** Per-status filter: "include" shows only those statuses, "exclude" hides them. */
    states?: Record<string, StateFilterMode>;
}
